<?xml version="1.0" ?>

<!DOCTYPE TkrGeometry [
<!ELEMENT TkrGeometry (section)* >
<!ATTLIST TkrGeometry cvs_Header CDATA #REQUIRED
                     cvs_Revision CDATA #REQUIRED>
<!ELEMENT section (#PCDATA | item | section)*  >
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT item   (#PCDATA)>
<!ATTLIST item  name CDATA #REQUIRED
                value CDATA #REQUIRED>
]>

<!--    GLAST digi constants
        Do not modify and check in this file without permission!
        Note that the text in the item field cannot have direct ampersands of brackets!
  -->
<TkrGeometry cvs_Header="$Header: /home/cvs/SLAC/TkrRecon/xml/Tkr_TestBeam.xml,v 1.1 2001/03/21 23:23:20 usher Exp $"
            cvs_Revision="$Revision: 1.1 $">

    <section name="tkr"> TKR properties
        <item name="numYtowers"      value="1">       Number of towers in Y direction </item>
		<item name="nViews"          value="2">       Number of views (X and Y) </item>
		<item name="nLayers"         value="16">      Total number of layers </item>
		<item name="nPbLayers"       value="14">      Number of layers with converter </item>
		<item name="nSuperGLayers"   value="3">       Number of layers with thick converter </item>
		<item name="indMixed"        value="14">      ?? </item>
		<item name="Z0"              value="0">       ?? </item>
		<item name="towerPitch"      value="0.0">     Tower pitch </item>
		<item name="trayWidth"       value="32.08">   Width of a tray </item>
		<item name="trayHeight"      value="3.20802"> Height of one tray </item>
		<item name="ladderWidth"     value="6.4">     Width of one ladder </item>
		<!--    Below uses the value for the 5-wafer ladder -->
		<item name="ladderLength"    value="32.012">   Length of one ladder </item>
		<item name="ladderGap"       value="0.02">    ?? </item>
		<item name="ladderInnerGap"  value="0.003">   ?? </item>
		<item name="ladderNStrips"   value="320">     Number strips/ladder </item>
		<item name="siStripPitch"    value="0.0194">  Strip pitch </item>
		<item name="siResolution"    value="0.0056">  Strip resolution </item>
		<item name="siThickness"     value="0.0400">  Thickness </item>
		<item name="siDeadDistance"  value="0.0960">  ?? </item>
		<item name="siX0"            value="9.3600">  Radiation lengths of silicon </item>
		<item name="pbX0"            value="0.56">    Radiation lengths of converter </item>
		<!--    From Eduardo -->
		<item name="thinConvHeight"  value="0.02032"> Thickness of "thin" converter </item>
		<item name="thickConvHeight" value="0.15748"> Thickness of "thick" converter </item>
    </section>

    <section name="cal"> CAL properties
    </section>

    <section name="acd">  ACD properties
	<item name="lowThreshold"     value="0.2"> MeV enables PHA</item>
        <item name="vetoThreshold"      value="0.4"> MeV nominal veto </item>
        <item name="highThreshold" value="20.0"> MeV CNO </item>
        <item name="adcChannelsPerMeV" value = "203.0793"> conversion from energy to ADC channels </item>
    </section>

</TkrGeometry>
